namespace FreeFlight.CabinControl.App.ViewModels;

internal static class BritishAirwaysStationCatalog
{
    // BA-operated destinations verified against the current route network for the v0.5.0 September 2026 pass.
    // Keep this catalog centralized so seasonal network changes can be updated without touching the DCS UI.
    public static IReadOnlyList<GateStationOption> All { get; } =
    [
        new("TIA", "Tirana (TIA)"),
        new("ALG", "Algiers (ALG)"),
        new("ANU", "St. John's, Antigua (ANU)"),
        new("EZE", "Buenos Aires (EZE)"),
        new("MEL", "Melbourne (MEL)"),
        new("SYD", "Sydney (SYD)"),
        new("GRZ", "Graz (GRZ)"),
        new("INN", "Innsbruck (INN)"),
        new("SZG", "Salzburg (SZG)"),
        new("VIE", "Vienna (VIE)"),
        new("NAS", "Nassau (NAS)"),
        new("BAH", "Bahrain (BAH)"),
        new("BGI", "Bridgetown (BGI)"),
        new("BRU", "Brussels (BRU)"),
        new("BDA", "Bermuda (BDA)"),
        new("GIG", "Rio de Janeiro (GIG)"),
        new("GRU", "Sao Paulo (GRU)"),
        new("SOF", "Sofia (SOF)"),
        new("KTI", "Phnom Penh (KTI)"),
        new("YUL", "Montreal (YUL)"),
        new("YYZ", "Toronto (YYZ)"),
        new("YVR", "Vancouver (YVR)"),
        new("GCM", "Grand Cayman (GCM)"),
        new("SCL", "Santiago (SCL)"),
        new("PVG", "Shanghai (PVG)"),
        new("SJO", "San Jose, Costa Rica (SJO)"),
        new("DBV", "Dubrovnik (DBV)"),
        new("SPU", "Split (SPU)"),
        new("ZAG", "Zagreb (ZAG)"),
        new("LCA", "Larnaca (LCA)"),
        new("PFO", "Paphos (PFO)"),
        new("PRG", "Prague (PRG)"),
        new("BLL", "Billund (BLL)"),
        new("CPH", "Copenhagen (CPH)"),
        new("PUJ", "Punta Cana (PUJ)"),
        new("CAI", "Cairo (CAI)"),
        new("SSH", "Sharm el-Sheikh (SSH)"),
        new("IVL", "Ivalo (IVL)"),
        new("RVN", "Rovaniemi (RVN)"),
        new("BSL", "Basel Mulhouse Freiburg (BSL)"),
        new("EGC", "Bergerac (EGC)"),
        new("BOD", "Bordeaux (BOD)"),
        new("CMF", "Chambery (CMF)"),
        new("FSC", "Figari (FSC)"),
        new("GNB", "Grenoble / Lyon (GNB)"),
        new("LYS", "Lyon (LYS)"),
        new("MRS", "Marseille (MRS)"),
        new("MPL", "Montpellier (MPL)"),
        new("NCE", "Nice (NCE)"),
        new("CDG", "Paris Charles de Gaulle (CDG)"),
        new("TLN", "Toulon (TLN)"),
        new("TLS", "Toulouse (TLS)"),
        new("TBS", "Tbilisi (TBS)"),
        new("BER", "Berlin (BER)"),
        new("CGN", "Cologne-Bonn (CGN)"),
        new("DUS", "Dusseldorf (DUS)"),
        new("FRA", "Frankfurt (FRA)"),
        new("HAM", "Hamburg (HAM)"),
        new("HAJ", "Hanover (HAJ)"),
        new("MUC", "Munich (MUC)"),
        new("NUE", "Nuremberg (NUE)"),
        new("ACC", "Accra (ACC)"),
        new("GIB", "Gibraltar (GIB)"),
        new("ATH", "Athens (ATH)"),
        new("CHQ", "Chania, Crete (CHQ)"),
        new("CFU", "Corfu (CFU)"),
        new("HER", "Heraklion, Crete (HER)"),
        new("KLX", "Kalamata (KLX)"),
        new("EFL", "Kefalonia (EFL)"),
        new("KGS", "Kos (KGS)"),
        new("JMK", "Mykonos (JMK)"),
        new("PVK", "Preveza / Lefkada (PVK)"),
        new("RHO", "Rhodes (RHO)"),
        new("JTR", "Santorini (JTR)"),
        new("JSI", "Skiathos (JSI)"),
        new("SKG", "Thessaloniki (SKG)"),
        new("ZTH", "Zakynthos (ZTH)"),
        new("GND", "Grenada (GND)"),
        new("GCI", "Guernsey (GCI)"),
        new("GEO", "Georgetown, Guyana (GEO)"),
        new("HKG", "Hong Kong (HKG)"),
        new("BUD", "Budapest (BUD)"),
        new("KEF", "Reykjavik Keflavik (KEF)"),
        new("BLR", "Bengaluru (BLR)"),
        new("MAA", "Chennai (MAA)"),
        new("HYD", "Hyderabad (HYD)"),
        new("BOM", "Mumbai (BOM)"),
        new("DEL", "New Delhi (DEL)"),
        new("DUB", "Dublin (DUB)"),
        new("TLV", "Tel Aviv (TLV)"),
        new("BRI", "Bari (BRI)"),
        new("BLQ", "Bologna (BLQ)"),
        new("BDS", "Brindisi (BDS)"),
        new("CAG", "Cagliari (CAG)"),
        new("CTA", "Catania (CTA)"),
        new("FLR", "Florence (FLR)"),
        new("LIN", "Milan Linate (LIN)"),
        new("MXP", "Milan Malpensa (MXP)"),
        new("NAP", "Naples (NAP)"),
        new("OLB", "Olbia (OLB)"),
        new("PMO", "Palermo (PMO)"),
        new("PEG", "Perugia (PEG)"),
        new("PSA", "Pisa (PSA)"),
        new("RMI", "Rimini (RMI)"),
        new("FCO", "Rome Fiumicino (FCO)"),
        new("TRN", "Turin (TRN)"),
        new("VCE", "Venice Marco Polo (VCE)"),
        new("VRN", "Verona (VRN)"),
        new("KIN", "Kingston (KIN)"),
        new("HND", "Tokyo Haneda (HND)"),
        new("JER", "Jersey (JER)"),
        new("AMM", "Amman (AMM)"),
        new("NBO", "Nairobi (NBO)"),
        new("LUX", "Luxembourg (LUX)"),
        new("KUL", "Kuala Lumpur (KUL)"),
        new("MLE", "Male (MLE)"),
        new("MLA", "Malta (MLA)"),
        new("MRU", "Mauritius (MRU)"),
        new("CUN", "Cancun (CUN)"),
        new("MEX", "Mexico City (MEX)"),
        new("TIV", "Tivat (TIV)"),
        new("AGA", "Agadir (AGA)"),
        new("RAK", "Marrakech (RAK)"),
        new("RBA", "Rabat (RBA)"),
        new("AMS", "Amsterdam (AMS)"),
        new("RTM", "Rotterdam (RTM)"),
        new("ABV", "Abuja (ABV)"),
        new("LOS", "Lagos (LOS)"),
        new("OSL", "Oslo Gardermoen (OSL)"),
        new("TOS", "Tromso (TOS)"),
        new("ISB", "Islamabad (ISB)"),
        new("KRK", "Krakow (KRK)"),
        new("WAW", "Warsaw (WAW)"),
        new("FAO", "Faro (FAO)"),
        new("FNC", "Funchal (FNC)"),
        new("LIS", "Lisbon (LIS)"),
        new("PDL", "Ponta Delgada (PDL)"),
        new("OPO", "Porto (OPO)"),
        new("DOH", "Doha (DOH)"),
        new("OTP", "Bucharest (OTP)"),
        new("RUH", "Riyadh (RUH)"),
        new("SIN", "Singapore (SIN)"),
        new("LJU", "Ljubljana (LJU)"),
        new("CPT", "Cape Town (CPT)"),
        new("JNB", "Johannesburg (JNB)"),
        new("ALC", "Alicante (ALC)"),
        new("BCN", "Barcelona (BCN)"),
        new("FUE", "Fuerteventura (FUE)"),
        new("LPA", "Gran Canaria (LPA)"),
        new("IBZ", "Ibiza (IBZ)"),
        new("ACE", "Lanzarote (ACE)"),
        new("MAD", "Madrid (MAD)"),
        new("AGP", "Malaga (AGP)"),
        new("MAH", "Menorca (MAH)"),
        new("PMI", "Palma de Mallorca (PMI)"),
        new("EAS", "San Sebastian (EAS)"),
        new("SVQ", "Seville (SVQ)"),
        new("TFS", "Tenerife South (TFS)"),
        new("VLC", "Valencia (VLC)"),
        new("CMB", "Colombo (CMB)"),
        new("SKB", "Saint Kitts (SKB)"),
        new("UVF", "Saint Lucia (UVF)"),
        new("GOT", "Gothenburg (GOT)"),
        new("ARN", "Stockholm Arlanda (ARN)"),
        new("GVA", "Geneva (GVA)"),
        new("ZRH", "Zurich (ZRH)"),
        new("BKK", "Bangkok (BKK)"),
        new("POS", "Port of Spain (POS)"),
        new("TAB", "Tobago (TAB)"),
        new("AYT", "Antalya (AYT)"),
        new("BJV", "Bodrum (BJV)"),
        new("DLM", "Dalaman (DLM)"),
        new("IST", "Istanbul (IST)"),
        new("PLS", "Providenciales (PLS)"),
        new("AUH", "Abu Dhabi (AUH)"),
        new("DXB", "Dubai (DXB)"),
        new("ABZ", "Aberdeen (ABZ)"),
        new("BHD", "Belfast City (BHD)"),
        new("EDI", "Edinburgh (EDI)"),
        new("GLA", "Glasgow (GLA)"),
        new("INV", "Inverness (INV)"),
        new("LCY", "London City (LCY)"),
        new("LGW", "London Gatwick (LGW)"),
        new("LHR", "London Heathrow (LHR)"),
        new("STN", "London Stansted (STN)"),
        new("MAN", "Manchester (MAN)"),
        new("NCL", "Newcastle (NCL)"),
        new("ATL", "Atlanta (ATL)"),
        new("AUS", "Austin (AUS)"),
        new("BWI", "Baltimore-Washington (BWI)"),
        new("BOS", "Boston (BOS)"),
        new("ORD", "Chicago O'Hare (ORD)"),
        new("CVG", "Cincinnati (CVG)"),
        new("DFW", "Dallas-Fort Worth (DFW)"),
        new("DEN", "Denver (DEN)"),
        new("IAH", "Houston Intercontinental (IAH)"),
        new("LAS", "Las Vegas (LAS)"),
        new("LAX", "Los Angeles (LAX)"),
        new("MIA", "Miami (MIA)"),
        new("BNA", "Nashville (BNA)"),
        new("MSY", "New Orleans (MSY)"),
        new("JFK", "New York JFK (JFK)"),
        new("EWR", "Newark (EWR)"),
        new("MCO", "Orlando (MCO)"),
        new("PHL", "Philadelphia (PHL)"),
        new("PHX", "Phoenix (PHX)"),
        new("PIT", "Pittsburgh (PIT)"),
        new("PDX", "Portland (PDX)"),
        new("SAN", "San Diego (SAN)"),
        new("SFO", "San Francisco (SFO)"),
        new("SEA", "Seattle / Tacoma (SEA)"),
        new("STL", "St. Louis (STL)"),
        new("TPA", "Tampa (TPA)"),
        new("IAD", "Washington Dulles (IAD)")
    ];
}
